version: 0.0.1.{build}
before_build:
- cmd: nuget restore
- ps: >-
    cd C:\projects\download-manager

    $VerFromAssemblyInfo = get-content VersionInfo.cs

    $InstallScript = get-content Install\DownloadManager.iss

    $VerFromAssemblyInfo[2][27]

    $i = 27

    $verString = ""

    do

    {

    $verString = $verString + $VerFromAssemblyInfo[2][$i]

    $i = $i + 1

    }

    while($VerFromAssemblyInfo[2][$i] -ne ')')

    $verString

    $InstallScript[1]

    $InstallScript[1] = "#define Version " + $verString

    $InstallScript[1]

    $InstallScript | set-content Install\DownloadManager.iss
build:
  project: DownloadManager.sln
  publish_wap: true
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
after_build:
- cmd: packages\Tools.InnoSetup.5.5.6\tools\ISCC Install\DownloadManager.iss
deploy:
- provider: GitHub
  description: Release DownloadManager from AppVeyor
  auth_token:
    secure: lsXNYVpjq9/wvgfxSx7/Ef6Om3WZD84ZJEbnWeqVXwWZoh3LRqpnQBhQqYDGpuTg
  artifact: DownloadManager\Install\Installer.zip